[tool.poetry]
name = "poetry-venv"
version = "0.1.0"
description = ""
authors = ["Evgen Bratenkov <giertrut@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
