"""added column 'type'

Revision ID: 17bd6b6625e4
Revises: a13a3473fe29
Create Date: 2024-08-08 16:20:54.150317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17bd6b6625e4'
down_revision: Union[str, None] = 'a13a3473fe29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Categories_pomodoro', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Categories_pomodoro', 'type')
    # ### end Alembic commands ###
