"""added column 'pomodoro_count'

Revision ID: f0123f86aa0b
Revises: 17bd6b6625e4
Create Date: 2024-08-08 16:24:29.982757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0123f86aa0b'
down_revision: Union[str, None] = '17bd6b6625e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_pomodoro', sa.Column('pomodoro_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks_pomodoro', 'pomodoro_count')
    # ### end Alembic commands ###
